### ISSUE TITLE
How to deal with printing content inside ember-light table

### ISSUE THREAD

**Issue by zuekut** [offirgolan/ember-light-table#526] opened 2017-12-07 13:08 UTC
Hello, 
In my project, I am trying to prepare an ember-light table for printing with a print.css stylesheet. I have multiple expanded rows, which in a printed format would take multiple pages. My issue is that, I cannot find a way to make ember-light table be visible in its full height, in other words to be able to print the entire content of the table. Because right now, only the part, to which I've scrolled to is visible, making it inconvenient for printing. Thank you in advance!

**Comment by buschtoens** [comment] 2017-12-07 13:57
We already have an issue for that:  https://github.com/offirgolan/ember-light-table/issues/471  :wink:

Concerning printing a scrollable table (with fixed header / footer), you'd need to overwrite the styles that set stuff like `overflow: scroll` and `position: absolute`.

**Comment by zuekut** [comment] 2017-12-07 14:14
@buschtoens Oh yes, I was just looking at this one, sorry about that. I followed what @Techn1x did and it worked pretty well, however it forced me to remove the height declaration, which killed the purpose a little bit of having the table be set in one place, without having to go down the page.

**Comment by buschtoens** [comment] 2017-12-11 06:54
Sounds like a CSS problem. I suggest manually "undoing" all styles set by `fixed=true` and incorporating what #471 does. Since this a duplicate of that issue, I'd rather not scatter the discussion about multiple issues and continue there.

**Closed by buschtoens** 2017-12-11 06:54 UTC
