### ISSUE TITLE
tableActions call also onRowClick

### ISSUE THREAD

**Issue by Luisetelo** [offirgolan/ember-light-table#269] opened 2016-11-21 10:10 UTC
Hi there, 

I have a table declared as follows: 
```
{{#light-table table tableActions=(hash delete=(action 'deleteModel')) as |t|}}
 Some code here...
{{#t.body onRowClick=onEdit tableClassNames="list bordered striped" as |body|}}
 Some code here...
  {{/t.body}}
{{/light-table}}
```
Every row has a button to delete the row. This button is declared as a cellType.
The problem is when I click that button both actions are called edit and delete.

**Comment by corrspt** [comment] 2016-11-21 10:18
Can you share the `cellType` code?

**Comment by Luisetelo** [comment] 2016-11-21 10:24
Sure, here is the relevant part of the code:

```
  actions: {
    cellAction() {
      const action = this.get('action');

      if (action && this.get(`tableActions.${action}`)) {
        this.get(`tableActions.${action}`)(this.get('row'));
      }
    },
  },
```

```
<a  {{action 'cellAction'}}>
  <i class="material-icons">{{materialIcon}}</i> {{value}}
</a>
```

**Comment by corrspt** [comment] 2016-11-21 10:33
I don't see anything wrong with that code, sorry. Would probably need an ember-twiddle with a reproduction case, does `const action = this.get('action')` return `edit` (or what you expect?)

**Comment by Luisetelo** [comment] 2016-11-21 10:40
In this case `this.get('action')` return `deleteModel` what is expected so everything it's ok. 

I will try to reproduce the error in an ember-twiddle.

**Comment by rstudner** [comment] 2016-11-30 21:18
I'm sort of in the same boat? (I think)

Basically if I have:
```
{{#t.body onRowClick=<anything here> 
```
Then I can't put anything clickable in a cel without the onRowClick also firing.

**Comment by buschtoens** [comment] 2016-12-01 04:44
That's because of the event bubbling. I'm only on my mobile right now, but
you can read up on it in the Ember guides. 😉

**Comment by Luisetelo** [comment] 2016-12-01 11:13
@rstudner Yes exactly! We are in the same boat :)

I don't catch your solution, which click method are you overriding in the cel component? The specific component action?

**Comment by rstudner** [comment] 2016-12-01 11:31
Yeah. Basically just;
my-cell-component/component.js has:
```
click() { return false; }
```

**Comment by offirgolan** [comment] 2016-12-01 11:52
Closing as the above solution will work. Just overwrite your custom cell component's click method and prevent bubbling by either using the given `event` object or returning `false`.

If you want to prevent the `{{action}}` from bubbling, a better solution can be found in [the event propagation docs](http://emberjs.com/api/classes/Ember.Templates.helpers.html#toc_event-propagation).

**Closed by offirgolan** 2016-12-01 11:52 UTC

**Comment by Luisetelo** [comment] 2016-12-01 15:13
Thank you guys, @rstudner solution worked perfectly :smile:
