### ISSUE TITLE
After latest upgrade scrollbar is not working in ember-light-table

### ISSUE THREAD

**Issue by vishalpareek** [offirgolan/ember-light-table#571] opened 2018-07-09 03:01 UTC
I have implemented the ember-light-table in my project, but after the latest upgrade the scrollbar in my table has stopped working. Is there any new configuration introduced in order to get the scrollbar.

**Comment by snewcomer** [comment] 2018-07-09 04:31
@vishalpareek Did `1.13.0` or `1.13.1` break for you?

**Comment by vishalpareek** [comment] 2018-07-10 01:54
I am getting this issue in 1.13.1.

**Comment by snewcomer** [comment] 2018-07-10 02:53
@vishalpareek Any issues with `1.13.0`?

**Comment by vishalpareek** [comment] 2018-07-10 02:55
I haven't tried with 1.13.0, i have upgraded it to the latest and now i am facing this issue. 

While building my application i am getting below warning,could this be a problem

DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least
 ember-cli-babel 6.6. Version 5.2.8 located: rdm-new-ui -> ember-light-table ->
ember-scrollable -> ember-component-inbound-actions -> ember-cli-babel
DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least
 ember-cli-babel 6.6. Version 5.2.8 located: rdm-new-ui -> ember-light-table ->
ember-scrollable -> ember-element-resize-detector -> ember-cli-babel

**Comment by snewcomer** [comment] 2018-07-10 03:36
Closer!  Would you mind trying out 1.13.0 and let us know if that is broken as well?  It will help us hone in on the problem since we don't have an exact reproduction of what you are seeing. 🙇

**Comment by tombakerjr** [comment] 2018-11-29 23:33
I was experiencing this same issue when upgrading from `1.12.2` to `1.13.x` (I tried them all). It turns out we use an instance initializer to set all of our tables to have fixed headers by default, so the `sharedOptions` refactor resulted in our `fixedHeader: true` on the `light-table` component being ignored. If I switch to setting `fixed: true` on the `lt-head` component, everything works as expected.

**Comment by fran-worley** [comment] 2019-05-26 11:00
I believe the confusion here is related to https://github.com/offirgolan/ember-light-table/issues/694 

Thanks @tombakerjr for posting a resolution - I'm going to close this as we can track via #694

**Closed by fran-worley** 2019-05-26 11:00 UTC
