### ISSUE TITLE
Resizable columns?

### ISSUE THREAD

**Issue by NegativeIQ** [offirgolan/ember-light-table#72] opened 2016-06-23 21:26 UTC
Hey guys i love light table, it has everything out of the box with a simple config, but is it possible to have resizable columns in any way?

**Comment by offirgolan** [comment] 2016-06-28 03:01
This is a duplicate of #18. This is something we would love to add, unfortunately, it will not be prioritized for the 1.0 release. A PR is always welcome 😺

**Closed by offirgolan** 2016-06-28 03:01 UTC
