### ISSUE TITLE
Wrong width calculation

### ISSUE THREAD

**Issue by MassimoScattarella** [offirgolan/ember-light-table#396] opened 2017-04-27 13:19 UTC
Problem: Table is larger than container
Description: I use paginated table and  scrollable container is more larger, columns are wide 
Resolve my problem with downgrade ember-scrollable at 0.4.4
Correct or are there any other problems?

Edit:  the problem is on ember-srollable 0.4.5

**Comment by MassimoScattarella** [comment] 2017-04-27 14:22
Sorry, the problem is on ember-srollable 0.4.5

**Comment by alexander-alvarez** [comment] 2017-04-28 14:07
@buschtoens any insights into this?
looking at https://github.com/alphasights/ember-scrollable/compare/0.4.4...0.4.5 I think that's the only relevant change

**Comment by buschtoens** [comment] 2017-04-28 14:56
Will take a look at this on Monday evening, hopefully.

**Comment by joshbuckley** [comment] 2017-04-28 16:28
Also came across this issue in mac chrome (but not firefox) when "always show scrollbars" is enabled in system settings. The width returned by the scrollbar-thickness service was 15px and that threw off the width of the table body. In this case the width calculation isn't needed because the scrollbars are rendered on top of the table. Turning off "always show scrollbars" also resolved the issue.

**Comment by marceloandrader** [comment] 2017-05-04 17:39
In one of our projects, we are also seeing this, with latest v 1.8.6 that installs scrollable 0.4.5 we see discrepancies between the widths of the header cells with the row cells. When I cloned ember-scrollable locally and linked in the project as 0.4.4 the problem goes away.

**Comment by MassimoScattarella** [comment] 2017-05-04 20:01
Exactly, the problem si scrollable 0.4.5

**Comment by buschtoens** [comment] 2017-05-08 14:15
Could y'all please post screenshots indicating the problem alongside some info on which browser and OS you're using? :)

I suspect that this problem only occurs on OS X.

**Comment by marceloandrader** [comment] 2017-05-08 15:23
This screenshot is on Chrome 58.0.3029 on Linux with ember-scrollable v 0.4.4

![screenshot from 2017-05-08 10-18-42](https://cloud.githubusercontent.com/assets/57552/25811201/1111bc40-33d8-11e7-8c20-28184dcba2a7.png)

This uses the same environment but with ember-scrollable v 0.4.5

![screenshot from 2017-05-08 10-20-44](https://cloud.githubusercontent.com/assets/57552/25811256/406824b6-33d8-11e7-9cda-8664ad577f38.png)

The table headers are not aligned with the row cells.

**Comment by MassimoScattarella** [comment] 2017-05-09 09:08
same problem on Windows

**Comment by buschtoens** [comment] 2017-05-09 10:51
Thanks @marceloandrader! 

![image](https://cloud.githubusercontent.com/assets/834636/25847287/bc996b7a-34b5-11e7-9c2c-06d4538ab168.png)

Yes indeed, it's an upstream bug in ember-scrollable. And I'm the one to blame. :sweat_smile: 

Tracking it here: https://github.com/alphasights/ember-scrollable/issues/76

**Comment by buschtoens** [comment] 2017-05-17 13:25
So sorry for the long hold up, folks. I had a lot of things on my to do list. :see_no_evil: 

I finally got around to fix this bug. It was caused by remnant `::scrollbar` pseudo selectors that set the width of the scollbar to `0` in Chrome, but only inside of the emulator `<div>`.

I submitted a PR (https://github.com/alphasights/ember-scrollable/pull/78) and as soon as it's merged, this is fixed. :raised_hands:

**Comment by buschtoens** [comment] 2017-05-18 06:25
`ember-scrollable@0.4.7` was just released, fixing this! :smiley:

**Comment by RustyToms** [comment] 2017-05-18 15:01
I was the only one on my team that ended up getting ember-scrollable 0.4.5, they all had 0.4.4 (which satisfies the package.json version requirements). They all thought I was crazy when I kept seeing this issue and nobody else did 😆  I started to think I was crazy too

**Comment by buschtoens** [comment] 2017-05-18 15:12
Haha. I'm very sorry for making you question your sanity. 😅

Perfect time to recommend [yarn](https://yarnpkg.com/). It's an npm client that assures everybody on the team and every build gets exactly the same versions of packages. It's also quite a bit faster than npm and resilient to network outages. 

ember-cli is already natively supporting it as well.

**Comment by RustyToms** [comment] 2017-05-18 15:18
Actually we are all using yarn, and keep our yarn versions updated. We have not always experienced that, especially not in this case. But this repo does not have a lockfile.

**Closed** 2017-05-18 18:50 UTC

**Comment by offirgolan** [comment] 2017-05-19 04:53
@RustyToms you should be able to resolve your yarn issue with a simple `yarn upgrade ember-light-table`
