### ISSUE TITLE
Compatibility with Ember-CLI v2.11

### ISSUE THREAD

**Issue by rstudner** [offirgolan/ember-light-table#320] opened 2017-01-29 01:16 UTC
Ember 2.11 moved ember-cli-shims to npm.  Not sure if this is the cause/related, but if you try to include ember-light-table v1.8.1 in a project, the app will fail to launch.

(to note, and i'm no expert -- it appears maybe it has to do with ember-scrollable)

<img width="881" alt="screen shot 2017-01-28 at 8 16 17 pm" src="https://cloud.githubusercontent.com/assets/209970/22401129/b1cde0b8-e596-11e6-885c-cc7d95401c07.png">

**Comment by offirgolan** [comment] 2017-01-29 02:45
This is a duplicate of #295. Currently waiting for a new version release on ember-scrollable to resolve the issue.

**Comment by rstudner** [comment] 2017-01-29 02:46
So sorry! 

I must have typo'd my search.  DIdn't mean to make a dupe/waste your time.

**Closed by offirgolan** 2017-01-29 02:45 UTC

**Comment by offirgolan** [comment] 2017-01-29 02:46
No worries 😄
