### ISSUE TITLE
Scroll container

### ISSUE THREAD

**Issue by kevinansfield** [offirgolan/ember-light-table#201] opened 2016-10-05 14:07 UTC
Back in v0.1.9 it was [possible to set the scrollContainer](https://github.com/offirgolan/ember-light-table/blob/v0.1.9/addon/mixins/table-scroll.js#L31) - is the same thing possible now that the addon is using `ember-in-viewport`?

The reason I'm asking is because it seems to have broken our acceptance tests when trying to upgrade from the old version. In the app everything works fine, in the acceptance tests Chrome never triggers the `onScrolledToBottom` action (interestingly FF is ok) - after some manual testing I think this is because it's checking the position against `window` rather than the scrollable container.

Our test problems may also have some relation to https://github.com/offirgolan/ember-light-table/issues/199 as the app itself is rendered inside of a zoomed container element, although for us a fixed header/footer makes no difference.

**Comment by offirgolan** [comment] 2016-10-20 23:46
@kevinansfield sorry for the late reply! I've been having similar issues attempting to test scroll functionality because of that same exact reason (I believe). I've been too busy with other features / work to take a closer into this. If you found a working solution please feel free to share! 😸

**Comment by offirgolan** [comment] 2017-01-30 19:39
Closing as this issue has been abandoned. Feel free to reopen if needed.

**Closed by offirgolan** 2017-01-30 19:39 UTC

**Comment by kevinansfield** [comment] 2018-04-17 22:33
No, I didn't find any solution, our infinite scroll tests ended up being commented out as our `ember-light-table` use was only in a beta area of our app. Still interested to see if there is a solution somewhere, when our table screen gets a redesign I'll revisit if we're still using this addon

**Comment by mkay581** [comment] 2018-04-18 12:43
Thanks @kevinansfield. Yeah for some reason `onScrolledToBottom` is just not firing in integration tests.

@offirgolan any idea why that would be? we are using 1.12.2 version of ember-light-table. I'm programmatically scrolling the `.tse-scroll-content` element to the bottom of the table. I've verified that data is in the table, but `onScrolledToBottom` is never called. It is called when interacting with the table in non-tests scenarios though.

**Comment by mkay581** [comment] 2018-04-18 15:12
@kevinansfield @offirgolan 

After researching it appears that [`didEnterViewport` in lt-infinity component](https://github.com/offirgolan/ember-light-table/blob/v1.12.2/addon/components/lt-infinity.js#L37-L39) never fires in integration tests! So programmatically scrolling in integration tests never triggers `onScrolledToBottom`. 

After tracking this down, it appears that there was a semi-related issue on ember-in-viewport package where the method wasn't firing (see https://github.com/DockYard/ember-in-viewport/issues/116 and https://github.com/DockYard/ember-in-viewport/issues/95. 

This issue seems to have been fixed in latest version of ember-in-viewport but this package is still using [an older version](https://github.com/offirgolan/ember-light-table/blob/v1.12.2/package.json#L32). Maybe upgrading this package would solve the issue?

**Comment by mkay581** [comment] 2018-04-18 15:52
FYI, I've submitted https://github.com/DockYard/ember-in-viewport/issues/142 to `ember-in-viewport`  package as I believe that is why `onScrolledToBottom` is not firing in integration tests.

**Comment by snewcomer** [comment] 2018-04-18 16:55
@mkay581 What version of Ember are you using (where the tests live)?  Not seeing a relevant one in this pkg.  

Also, I might take another stab at #548; however, there was talk about making `occlusion rendering` the default, thus no need for using `ember-in-viewport`.

**Comment by mkay581** [comment] 2018-04-18 17:26
I'm using Ember 2.16.2. Does that help at all?

**Comment by mkay581** [comment] 2018-04-19 14:38
@snewcomer I took a look and looks like https://github.com/offirgolan/ember-light-table/pull/548 won't fix this issue because the problem is that `didEnterViewport` never gets called because the `ember-in-viewport` default configs are not being used so its `viewportEnabled` is never set to true in integration tests inside of an addon. I opened https://github.com/DockYard/ember-in-viewport/issues/142 to point this out.

**Comment by mkay581** [comment] 2018-04-20 02:40
Its hard to tell from your screenshots but are you running the integration tests from the "dummy" namespace in an addon?

**Comment by mkay581** [comment] 2018-04-22 16:58
I've worked with @snewcomer via slack and it appears that his PR https://github.com/offirgolan/ember-light-table/pull/548 seems to have fixed the issue.
