### ISSUE TITLE
targetScrollOffset Error and scrollbar visible

### ISSUE THREAD

**Issue by bugduino** [offirgolan/ember-light-table#323] opened 2017-02-01 10:02 UTC
I have a simple table in a template 

```
{{#light-table table height='50vh' as |t|}}
  {{t.head
    onColumnClick=(action 'onColumnClick')
    iconAscending='fa fa-sort-asc'
    iconDescending='fa fa-sort-desc'
    fixed=true}}

  {{#t.body
    canSelect=false
    canExpand=true
    multiRowExpansion=false
    onScrolledToBottom=(action 'onScrolledToBottom')
    as |body|}}
    {{#body.expanded-row as |row|}}
      <div>
        {{#each foo as |msg|}}
          <p>{{msg.name}}: {{msg.value}}</p>
        {{/each}}
      </div>
    {{/body.expanded-row}}
  {{/t.body}}
{{/light-table}}
```
when I expand a row and the expanded content overflows the table height, the scrollbar appears and that's ok. The problem is that when the expanded row is collapsed the scrollbar reamins visibile, and If I try to click on it a lot of errors are thrown in the console 

```
Assertion Failed: You modified "targetScrollOffset" twice on 
<phoenix-client@component:lt-body::ember573> in a single render. 
It was rendered in "component:lt-scrollable" and modified in "component:ember-scrollbar". 
This was unreliable and slow in Ember 1.x and is no longer supported. 
See https://github.com/emberjs/ember.js/issues/13948 for more details.
```

**Comment by alexander-alvarez** [comment] 2017-02-01 14:50
What version of `ember-light-table`? Can you reproduce in a twiddle?

**Comment by bugduino** [comment] 2017-02-01 14:58
1.8.2 . I'm trying to reproduce it

**Comment by bugduino** [comment] 2017-02-01 15:05
I'm not able to correctly include and build ember-light-table in ember twiddle, could you help me?

**Comment by alexander-alvarez** [comment] 2017-02-01 15:15
my bad, I forgot `ember-light-table` is on sass, and `ember-twiddle` currently doesn't support.
Can you reproduce on the demo page in a branch?

**Comment by bugduino** [comment] 2017-02-01 15:49
Here you have it https://github.com/offirgolan/ember-light-table/compare/master...bugduino:test-scroll-bar just start the server go to `http://localhost:4200/#/expandable` open one row, scroll and close the row. The scrollbar remains visible

**Comment by offirgolan** [comment] 2017-02-01 18:04
@alexander-alvarez you can also see this happening in the deployed demo app. 

1. The scrollbar doesnt auto hide
2. On first click (not drag) of the scrollbar, it scrolls back to the top

**Comment by alexander-alvarez** [comment] 2017-02-01 22:27
I'll take a look

**Comment by alexander-alvarez** [comment] 2017-02-02 16:42
@bugduino What os/browser? I'm on `chrome 54.0.2840.71` and cant reproduce the issue you're seeing.

@offirgolan I can't reproduce 1. I'll investigate why 2 happens

**Comment by bugduino** [comment] 2017-02-02 16:52
@alexander-alvarez I'm on `chrome Version 56.0.2924.76 (64-bit)` on linux

**Comment by offirgolan** [comment] 2017-02-07 19:33
@bugduino should be fixed now. Please re-install ember-light-table so it grabs the latest version of ember-scrollable.

**Comment by bugduino** [comment] 2017-02-08 09:45
I'm seeing the same behaviour with these deps 
```
phoenix-client@0.0.0
└─┬ ember-light-table@1.8.2
  └── ember-scrollable@0.4.1 
```

**Comment by offirgolan** [comment] 2017-02-08 21:29
@bugduino im not able to recreate the issues. See the demo page and let me know if you find anything.

**Comment by bugduino** [comment] 2017-02-10 15:25
I tried to pull and reinstall all deps for the v1.8.3 but and merged in my fork but I have the same problem (scroll bar remains visible even after the expandable row content is collapsed).
In the image below there is nothing to scroll
![screenshot](https://cloud.githubusercontent.com/assets/1852109/22832193/6037cd42-efad-11e6-8c49-cfcfb68c0eef.png)

**Comment by offirgolan** [comment] 2017-02-27 20:32
@bugduino I'm still not able to reproduce this. Can you try it in an ember-twiddle and see if you can reproduce it?

**Comment by bugduino** [comment] 2017-03-02 17:23
@offirgolan 
cannot reproduce with ember-twiddle because ember-light-table uses sass

**Comment by offirgolan** [comment] 2017-03-02 20:37
@bugduino the latest version of ELT has no sass dependencies.

**Comment by bugduino** [comment] 2017-03-02 22:11
https://ember-twiddle.com/5d87f45ca28fac235a8b13f65fd91a40*

At the beggining content of the table should not overflow, after expanding a row the scrollbar appears correctly.
If you collapse the row and move the mouse around (table hover out, hover in) the scrollbar is visible.

**Comment by offirgolan** [comment] 2017-03-03 00:02
@bugduino that is intended behavior. The scrollbar will auto hide if you stop moving the mouse or you move the mouse out side of the table.

**Comment by alexander-alvarez** [comment] 2017-03-03 00:15
@offirgolan the scrollbar continues to show up, even though there's no overflow.. I'm investigating a bit

**Comment by offirgolan** [comment] 2017-03-03 00:23
Sorry but I'm still not able to recreate this issue.

**Comment by alexander-alvarez** [comment] 2017-03-03 00:25
you can see it a lot clearer here:
https://github.com/alphasights/ember-scrollable/compare/master...alexander-alvarez:demonstrate-overflow

**Comment by alexander-alvarez** [comment] 2017-03-03 01:35
see https://github.com/alphasights/ember-scrollable/pull/58

**Closed** 2017-03-03 01:45 UTC
